/* Generated By:JavaCC: Do not edit this line. FormulaParserConstants.java */
package formulaParser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface FormulaParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ONCE = 5;
  /** RegularExpression Id. */
  int WHILE = 6;
  /** RegularExpression Id. */
  int LESS = 7;
  /** RegularExpression Id. */
  int TURN = 8;
  /** RegularExpression Id. */
  int OFF = 9;
  /** RegularExpression Id. */
  int WRB = 10;
  /** RegularExpression Id. */
  int WDT = 11;
  /** RegularExpression Id. */
  int NN = 12;
  /** RegularExpression Id. */
  int NNS = 13;
  /** RegularExpression Id. */
  int NNP = 14;
  /** RegularExpression Id. */
  int CD = 15;
  /** RegularExpression Id. */
  int CC = 16;
  /** RegularExpression Id. */
  int RBS = 17;
  /** RegularExpression Id. */
  int MD = 18;
  /** RegularExpression Id. */
  int VB = 19;
  /** RegularExpression Id. */
  int VBD = 20;
  /** RegularExpression Id. */
  int VBG = 21;
  /** RegularExpression Id. */
  int VBN = 22;
  /** RegularExpression Id. */
  int VBP = 23;
  /** RegularExpression Id. */
  int VBZ = 24;
  /** RegularExpression Id. */
  int IN = 25;
  /** RegularExpression Id. */
  int JJ = 26;
  /** RegularExpression Id. */
  int JJS = 27;
  /** RegularExpression Id. */
  int JJR = 28;
  /** RegularExpression Id. */
  int RB = 29;
  /** RegularExpression Id. */
  int START = 30;
  /** RegularExpression Id. */
  int MONITORING = 31;
  /** RegularExpression Id. */
  int WITH = 32;
  /** RegularExpression Id. */
  int END = 33;
  /** RegularExpression Id. */
  int DT = 34;
  /** RegularExpression Id. */
  int PDT = 35;
  /** RegularExpression Id. */
  int RP = 36;
  /** RegularExpression Id. */
  int PRP = 37;
  /** RegularExpression Id. */
  int TOPRE = 38;
  /** RegularExpression Id. */
  int HYPH = 39;
  /** RegularExpression Id. */
  int IDENTIFIER = 40;
  /** RegularExpression Id. */
  int LETTER = 41;
  /** RegularExpression Id. */
  int DIGIT = 42;
  /** RegularExpression Id. */
  int BOOL_LITERAL = 43;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"once\"",
    "\"while\"",
    "\"less\"",
    "\"turn\"",
    "\"off\"",
    "\"WRB\"",
    "\"WDT\"",
    "\"NN\"",
    "\"NNS\"",
    "\"NNP\"",
    "\"CD\"",
    "\"CC\"",
    "\"RBS\"",
    "\"MD\"",
    "\"VB\"",
    "\"VBD\"",
    "\"VBG\"",
    "\"VBN\"",
    "\"VBP\"",
    "\"VBZ\"",
    "\"IN\"",
    "\"JJ\"",
    "\"JJS\"",
    "\"JJR\"",
    "\"RB\"",
    "\"Start\"",
    "\"Monitoring\"",
    "\"With\"",
    "\"End\"",
    "\"DT\"",
    "\"PDT\"",
    "\"RP\"",
    "\"PRP\"",
    "\"TO\"",
    "\"HYPH\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "<BOOL_LITERAL>",
    "\",\"",
    "\".\"",
    "\";\"",
  };

}
